//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Casino.AdminPortal.EntityDataModel.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerTable
    {
        public string CustomerName { get; set; }
        public System.DateTime DOB { get; set; }
        public string Contact { get; set; }
        public string EmailId { get; set; }
        public byte[] IdProof { get; set; }
        public decimal AccountBalance { get; set; }
        public int BlockBalance { get; set; }
        public int CustomerId { get; set; }
    }
}
